baseURL = "https://midwestsec.com"
languageCode = "en-us"
title = "MidwestSec"
theme = "hugo-theme-stack"

[pagination]
  pagerSize = 10

[params]
  mainSections = ["posts"]
  featuredImageField = "image"
  rssFullContent = true
  custom_css = ["scss/custom.scss"]

[params.comments]
  enabled = false

[params.sidebar]
  subtitle = "Just a Guy Learning"
  avatar = "images/MidwestSec_bw.png"

[params.article]
  math = false
  toc = true
  readingTime = true
  headingAnchor = true

[[params.widgets.page]]
  type = "toc"

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false

[params.footer]
  since = 2026
  customText = ""

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[menu.main]]
identifier = "whoami"
name = "whoami"
url = "/whoami/"
weight = 20

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 30

[[menu.main]]
identifier = "walkthroughs"
name = "Walkthroughs"
url = "/walkthroughs/"
weight = 40

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 50
